version: '3.5'
services:
    dart-server:
        restart: always
        image: dartrinha
        ports:
            - "8080:8080"
        depends_on: 
            - db
        networks:
        - my-networks   
        
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - my-db:/var/lib/mysql
        networks:
        - my-networks      
volumes:
    my-db:
networks:
  my-networks:
    driver: bridge