version: '3.7'
services:
    dart-server:
        restart: always
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
        image: dartrinha
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        depends_on: 
            - db
        networks:
        - localhost
        
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - '${DB_PORT}:${DB_PORT}'
        volumes:
            - my-db:/var/lib/mysql
        networks:
        - localhost
volumes:
    my-db:
networks:
  localhost:
    driver: bridge