name: rinha
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  mysql_client: ^0.0.27
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.0
  uuid: ^4.0.0

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.0
  test: ^1.24.0
  test_process: ^2.1.0
